version: '3.7'
services:
  data_virtualization:
    image: gioppoluca/teiid:12.1.0
    hostname: teiid
#    environment:
#      JAVA_OPTS: "-Dfile.encoding=UTF-8"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "31000:31000"
      - "35432:35432"
    volumes:
      - ./teiid/deployments:/opt/jboss/wildfly/standalone/deployments
      - ./teiid/configuration/standalone-teiid.xml:/opt/jboss/wildfly/standalone/configuration/standalone-teiid.xml
      - ./teiid/modules/org/postgresql:/opt/jboss/wildfly/modules/system/layers/base/org/postgresql
      - ./teiid/csv:/csv
      - ./teiid/configuration/application-roles.properties:/opt/jboss/wildfly/standalone/configuration/application-roles.properties
      - ./teiid/configuration/application-users.properties:/opt/jboss/wildfly/standalone/configuration/application-users.properties
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - micado_net


  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://postgrest:3000/
    depends_on:
      - data_api

  node:
    image: node:10.16.0
    ports:
      - "8081:8081"
    volumes:
      - ./nodejs:/home/node/app
    networks:
      - micado_net
    working_dir: /home/node/app
    user: "node"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: "nodejs ./httprequestdump.js"



volumes:
