version: '3.7'
services:
  data_virtualization:
    image: gioppoluca/teiid:12.1.0
    hostname: teiid
#    environment:
#      JAVA_OPTS: "-Dfile.encoding=UTF-8"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "31000:31000"
      - "35432:35432"
    volumes:
      - ./teiid/deployments:/opt/jboss/wildfly/standalone/deployments
      - ./teiid/configuration/standalone-teiid.xml:/opt/jboss/wildfly/standalone/configuration/standalone-teiid.xml
      - ./teiid/modules/org/postgresql:/opt/jboss/wildfly/modules/system/layers/base/org/postgresql
      - ./teiid/csv:/csv
      - ./teiid/configuration/application-roles.properties:/opt/jboss/wildfly/standalone/configuration/application-roles.properties
      - ./teiid/configuration/application-users.properties:/opt/jboss/wildfly/standalone/configuration/application-users.properties
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - micado_net

  rocketchat:
    image: rocketchat/rocket.chat:3.6.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
#    restart: unless-stopped
    volumes:
      - ./rc_uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - MAIL_URL=smtp://smtp.email
#       - HTTP_PROXY=http://proxy.domain.com
#       - HTTPS_PROXY=http://proxy.domain.com
#    depends_on:
#      - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"
    networks:
      - micado_net

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://postgrest:3000/
    depends_on:
      - data_api

  node:
    image: node:10.16.0
    ports:
      - "8081:8081"
    volumes:
      - ./nodejs:/home/node/app
    networks:
      - micado_net
    working_dir: /home/node/app
    user: "node"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: "nodejs ./httprequestdump.js"



#volumes:
