[ENVI_VAR]
env_api_hostname = "$env{API_HOSTNAME}"


[server]
hostname = "$env{IDENTITY_HOSTNAME}"
node_ip = "0.0.0.0"
#base_path = "https://$ref{server.hostname}"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
serverDetails = "WSO2 IS as KM 5.9.0"
mode = "single"
userAgent = "WSO2 IS as KM 5.9.0"

[super_admin]
username = "$env{WSO2_IDENTITY_ADMIN_USER}"
password = "$env{WSO2_IDENTITY_ADMIN_PWD}"
create_admin_account = true

[user_store]
type = "database"
scim_enabled = true

[database.apim_db]
type = "postgre"
url = "jdbc:postgresql://micado_db:5432/$env{POSTGRES_DB}"
username = "$env{WSO2_API_USER}"
password = "$env{WSO2_API_PWD}"
driver = "org.postgresql.Driver"
validationQuery = "SELECT 1"
pool_options.maxActive = 50
pool_options.maxWait = 30000

#[database.apim_db]
#type = "h2"
#url = "jdbc:h2:./repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE"
#username = "wso2carbon"
#password = "wso2carbon"


#[database.config]
#type = "h2"
#url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE"
#username = "wso2carbon"
#password = "wso2carbon"

[database.shared_db]
type = "postgre"
url = "jdbc:postgresql://micado_db:5432/$env{POSTGRES_DB}"
username = "$env{WSO2_SHARED_USER}"
password = "$env{WSO2_SHARED_PWD}"
driver = "org.postgresql.Driver"
validationQuery = "SELECT 1"
pool_options.maxActive = 100
pool_options.maxWait = 10000
pool_options.validationInterval = 10000

#[database.shared_db]
#type = "h2"
#url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE"
#username = "wso2carbon"
#password = "wso2carbon"


#[keystore.primary]
#name = "wso2carbon.jks"
#password = "wso2carbon"

[keystore.primary]
file_name = "micadokeystore.jks"
password = "micadostorepass"
alias = "micadocert"
key_password = "micadokeypass"

[truststore]
file_name = "micado-truststore.jks"
password = "wso2carbonmicado"


[identity]
data_source = "jdbc/WSO2AM_DB"

[identity.auth_framework.endpoint]
#tenant_list_enabled="false"
hostname_verification_enabled="false"


[authentication.consent]
data_source = "jdbc/WSO2AM_DB"
prompt = true

[transport.https.sslHostConfig.properties]
certificateVerification = "want"

#[transport.http.properties]
#proxyPort = 80
#[transport.https.properties]
#proxyPort = 443

[tasks]
client_dispatch_address = "https://$ref{server.hostname}:9448"
server_address = "https://$ref{server.hostname}:443"

[oauth]
prompt_consent = "$ref{authentication.consent.prompt}"

[oauth.scope_validator.xacml]
enable = true

[oauth.grant_type.uma_ticket]
enable = true

[identity_mgt.user_self_registration]
allow_self_registration = true

[identity_mgt.user_onboarding]
enable_email_verification = false
lock_on_creation=false

[default_cache_timeout]
force_local_cache = true

[event.default_listener.mutual_tls_authenticator]
priority = ""
enable = false

[[event_listener]]
id = "mutual_tls_authenticator"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.carbon.identity.oauth2.token.handler.clientauth.mutualtls.MutualTLSClientAuthenticator"
order = "158"
enable = false

[event.default_listener.identity_mgt]
priority= "50"
enable = false
[event.default_listener.governance_identity_mgt]
priority= "95"
enable = true
[event.default_listener.governance_identity_store]
priority= "97"
enable = true

[oauth.extensions]
token_generator = "org.wso2.carbon.apimgt.keymgt.issuers.APIMTokenIssuer"

[apim.throttling]
enable_data_publishing = false
enable_policy_deploy = false
enable_blacklist_condition = false
enable_decision_connection = false
#receiver_url = "tcp://localhost:9611"
#receiver_auth_url = "ssl://localhost:9711"

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://{{ENVI_VAR.env_api_hostname}}:9611"]
traffic_manager_auth_urls=["ssl://{{ENVI_VAR.env_api_hostname}}:9711"]

[[apim.gateway.environment]]
name = "Production and Sandbox"
type = "hybrid"
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url = "https://{{ENVI_VAR.env_api_hostname}}/services/"
username= "$env{WSO2_API_ADMIN_USER}"
password= "$env{WSO2_API_ADMIN_PWD}"

[apim.jwt]
enable = true
#encoding = "base64" # base64,base64url
#generator_impl = "org.wso2.carbon.apimgt.keymgt.token.JWTGenerator"
#claim_dialect = "http://wso2.org/claims"
#header = "X-JWT-Assertion"
#signing_algorithm = "SHA256withRSA"
enable_user_claims = true
claims_extractor_impl = "org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever"

[output_adapter.email]
from_address= "development@micadoproject.eu"
username= "$env{WEBLATE_ADMIN_EMAIL}"
password= "$env{WEBLATE_EMAIL_HOST_PASSWORD}"
hostname= "$env{WEBLATE_EMAIL_HOST}"
port= 587
enable_start_tls= true
enable_authentication= true

[admin_service.wsdl]
enable = true

[output_adapter.email.custom_properties]
"mail.smtp.proxy.host"="10.138.149.7"
"mail.smtp.proxy.port"="3128"
