[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["0.0.0.0/0"]
  [entryPoints.web-secure]
    address = ":443"

[api]
  insecure = true

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

  [providers.file]
    filename = "/etc/traefik/dynamic.toml"
    watch = true

[accessLog]
  filePath = "/var/log/access.log"
#  format = "foobar"
#  bufferingSize = 42
#  [accessLog.filters]
#    statusCodes = ["400-499"]
#    retryAttempts = true
#    minDuration = 42


[certificatesResolvers.myresolver.acme]

  # Email address used for registration.
  #
  # Required
  #
  email = "development@micadoproject.eu"

  # File or key used for certificates storage.
  #
  # Required
  #
  storage = "acme.json"

  [certificatesResolvers.myresolver.acme.tlsChallenge]
